name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/php8.4-fpm
        tags: |
          # Tags pour les branches
          type=ref,event=branch,prefix=branch-
          # Tags pour les pull requests
          type=ref,event=pr,prefix=pr-
          # Tag latest pour la branche main uniquement
          type=raw,value=latest,enable={{is_default_branch}}
          # Tag stable pour la branche main
          type=raw,value=stable,enable={{is_default_branch}}
          # Tags basés sur le commit SHA
          type=sha,prefix={{branch}}-,format=short
          type=sha,prefix=commit-,format=long
          # Tags basés sur la date (format YYYYMMDD)
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=schedule,pattern={{date 'YYYYMMDD-HHmmss'}}
          # Tags pour les versions sémantiques (si tags Git présents)
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          # Tag d'environnement de développement
          type=raw,value=dev,enable={{is_default_branch}}
        labels: |
          org.opencontainers.image.title={{.Name}}
          org.opencontainers.image.description=PHP 8.4 FPM Docker Image
          org.opencontainers.image.vendor=${{ github.repository_owner }}
          org.opencontainers.image.version={{.Tag}}
          org.opencontainers.image.created={{.Date}}
          org.opencontainers.image.revision={{.FullCommit}}
          org.opencontainers.image.source={{.GitURL}}
          org.opencontainers.image.url=https://github.com/${{ github.repository }}
          org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/README.md

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
